Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Zilla.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace Zilla.Controllers
{
    [Authorize(Roles = "Administrator, User")]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Comments
        public async Task<ActionResult> Index()
        {
            if (HttpContext.User.IsInRole("Administrator"))
            {
                return View(await db.Comments.ToListAsync());
            }
            TempData["Toast"] = new Toast
            {
                Title = "Project",
                Body = "Access unauthorized!",
                Type = ToastType.Danger
            };
            return RedirectToAction("Index", "Home");
        }

        // GET: Comments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = await db.Comments.FindAsync(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(comment.Assignment.Project) || au.MemberInProjects.Contains(comment.Assignment.Project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Comment",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CommentId,Content,CreationDate")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = await db.Comments.FindAsync(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(comment.Assignment.Project) || au.MemberInProjects.Contains(comment.Assignment.Project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Comment",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Details", "Assignments", new { id = comment.Assignment.AssignmentId });
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CommentId,Content,CreationDate")] Comment comment)
        {
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(comment.Assignment.Project) || au.MemberInProjects.Contains(comment.Assignment.Project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Comment",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Assignments", new { id = comment.Assignment.AssignmentId });
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = await db.Comments.FindAsync(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(comment.Assignment.Project) || au.MemberInProjects.Contains(comment.Assignment.Project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Comment",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Comment comment = await db.Comments.FindAsync(id);
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(comment.Assignment.Project) || au.MemberInProjects.Contains(comment.Assignment.Project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Comment",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            var aid = comment.Assignment.AssignmentId;
            db.Comments.Remove(comment);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Assignments", new { id = aid });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Zilla.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Web.Security;
using System.Data.Entity.Validation;

namespace Zilla.Controllers
{
    [Authorize(Roles = "Administrator, User")]
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Projects
        public async Task<ActionResult> Index()
        {
            if (HttpContext.User.IsInRole("Administrator"))
            {
                return View(await db.Projects.ToListAsync());
            }
            TempData["Toast"] = new Toast
            {
                Title = "Project",
                Body = "Access unauthorized!",
                Type = ToastType.Danger
            };
            return RedirectToAction("Index", "Home");
        }

        // GET: Projects/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(project) || au.MemberInProjects.Contains(project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Project",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            return View(project);
        }

        // GET: Projects/Members/5
        public async Task<ActionResult> Members(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(project) || au.MemberInProjects.Contains(project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Project",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            return View(
                new MembersViewModel { Project = project, Members = project.Members }
            );
        }

        // POST: Projects/Members/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Members([Bind(Include = "ProjectId,Members")] Project project)
        {
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(project) || au.MemberInProjects.Contains(project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Project",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/AddMember/5
        public async Task<ActionResult> AddMember(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(project) || au.MemberInProjects.Contains(project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Project",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            //return View();
            ICollection<ApplicationUser> users = await db.Users.ToListAsync();
            users = users.Except(project.Members).ToList();
            return View(
                new AddMemberViewModel { 
                    Project = project, 
                    Users = users.Select(x => new SelectListItem()
                    {
                        Selected = false,
                        Text = x.UserName,
                        Value = x.UserName
                    })
                }
            );
            
        }
        // POST: Projects/AddMember/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddMember(
            string id,
            AddMemberViewModel model)
        {
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            Project project = await db.Projects.FindAsync(int.Parse(id));
            if (!(au.OrganizerInProjects.Contains(project) || au.MemberInProjects.Contains(project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Project",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                foreach(string username in model.AddedMembers)
                {
                    ApplicationUser user = await UserManager.FindByNameAsync(username);
                    user = db.Users.Find(user.Id);
                    if (user != null)
                        //db.ProjectMembers.Add(new ProjectMembers {
                        //    ProjectId = t.ProjectId, 
                        //    ApplicationUserId = user.Id });
                        project.Members.Add(user);

                }

                await db.SaveChangesAsync();

                TempData["Toast"] = new Toast {
                    Title = "Project",
                    Body = "Member successfully added!",
                    Type = ToastType.Success
                };

                return RedirectToAction("Details", new { id = project.ProjectId });
            }
            TempData["Toast"] = new Toast
            {
                Title = "Project",
                Body = "Member add unsuccessful!",
                Type = ToastType.Danger
            };
            return View(model);
        }

        // Get: Projects/RemoveMember/5/1
        public async Task<ActionResult> RemoveMember (string id, string memberIndex)
        {
            if (id == null || memberIndex == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Project project = await db.Projects.FindAsync(int.Parse(id));
            if (project == null)
            {
                return HttpNotFound();
            }

            ApplicationUser user = project.Members.ElementAt(int.Parse(memberIndex));
            if (user == null)
            {
                return HttpNotFound();
            }
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            if (!(au.OrganizerInProjects.Contains(project) || au.MemberInProjects.Contains(project) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast
                {
                    Title = "Project",
                    Body = "Access unauthorized!",
                    Type = ToastType.Danger
                };
                return RedirectToAction("Index", "Home");
            }

            return View(
                new RemoveMemberViewModel
                {
                    Project = project,
                    User = user
                }
            );

        }
        // DELETE: Projects/RemoveMember/5
        [HttpDelete]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveMember(
            string id,
            string memberIndex,
            RemoveMemberViewModel model)
        {
            ApplicationUser au = db.Users.Find(HttpContext.User.Identity.GetUserId());
            Project p = await db.Projects.FindAsync(int.Parse(id));
            if (!(au.OrganizerInProjects.Contains(p) || au.MemberInProjects.Contains(p) || UserManager.IsInRole(au.Id, "Administrator")))
            {
                TempData["Toast"] = new Toast

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1 class="pageHeading">
        <i class="fas fa-question" data-fa-transform="shrink-1 up-2 right-2" style="background:#EF9A9A"></i>
    <span>@ViewBag.Title.</span>
</h1>
<h2 class="pageSubheading">
    <span>@ViewBag.Message</span>
    <a class="btn btn-primary text-white float-right mr-1" href="@Url.Action("Index", "Home")">
        <i class="fas fa-arrow-left"></i> Back
    </a>
</h2>
<div class="pageContent">
    <div class="lead text-center">
        <p>Gojira(ゴジラ) → Godzila</p>
        <p>Jira → ???</p>
        <p>Useri → Monstri</p>
        <p>Proiecte → Orase</p>
        <p>Task-uri → Cladiri</p>
    </div>
</div>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h1 class="pageHeading">
    <i class="fas fa-at" data-fa-transform="shrink-1 up-2 right-2" style="background:#EF9A9A"></i>
    <span>@ViewBag.Title.</span>
</h1>
<h2 class="pageSubheading">
    <span>@ViewBag.Message</span>
    <a class="btn btn-primary text-white float-right mr-1" href="@Url.Action("Index", "Home")">
        <i class="fas fa-arrow-left"></i> Back
    </a>
</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Dashboard.cshtml
@model Zilla.Models.ApplicationUser

@{
    ViewBag.Title = "Dashboard";
}
<h1 class="pageHeading">
    <i class="fas fa-desktop" data-fa-transform="shrink-1 up-2 right-2" style="background:#EF9A9A"></i>
    <span>@ViewBag.Title.</span>
</h1>
<h2 class="pageSubheading">
    <span>@ViewBag.Message</span>
    <a class="btn btn-primary text-white float-right mr-1" href="@Url.Action("Index", "Home")">
        <i class="fas fa-arrow-left"></i> Back
    </a>
</h2>
<div class="pageContent">
    <div id="dashboard">
        <div id="userProjects">
            <h3>
                <i class="fas fa-city" data-fa-transform="shrink-1 up-2 right-2" style="background:#EF9A9A"></i>
                My Projects
                <a class="btn btn-primary text-white float-right" href="@Url.Action("Create", "Projects")">
                    <i class="fas fa-plus"></i> Create Project
                </a>
            </h3>
            <div>
                <div class="list-group">
                    @foreach (var project in Model.MemberInProjects.Union(Model.OrganizerInProjects))
                    {
                        <a href="@Url.Action("Details", "Projects", new { id = project.ProjectId})"
                           class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">
                                    @Html.DisplayFor(modelItem => project.Title)
                                </h5>
                            </div>
                            <p class="mb-1">
                                @Html.DisplayFor(modelItem => project.Description)
                            </p>
                            @if (project.Members.Contains(Model))
                            {
                                <small class="badge badge-info">Member</small>
                            }
                            @if (project.Organizers.Contains(Model))
                            {
                                <small class="badge badge-danger">Organizer</small>
                            }
                        </a>
                    }
                </div>
            </div>
        </div>
        <div id="userAssignments">
            <h3>
                <i class="fas fa-building" data-fa-transform="shrink-1 up-2 right-2" style="background:#EF9A9A"></i>
                My Assignments
            </h3>
            <div>
                <div class="list-group">
                    @foreach (var project in Model.MemberInProjects.Union(Model.OrganizerInProjects))
                    {
                        foreach (var assignment in project.Assignments.Where(a => a.Assignee == Model))
                        {
                            <a href="@Url.Action("Details", "Assignments", new { id = assignment.AssignmentId })"
                               class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        @Html.DisplayFor(modelItem => project.Title) | @Html.DisplayFor(modelItem => assignment.Title)
                                    </h5>
                                </div>
                                <small>
                                    @Html.DisplayFor(modelItem => assignment.StartDate) - @Html.DisplayFor(modelItem => assignment.EndDate)
                                </small>
                            </a>
                        }
                    }
                </div>
            </div>
        </div>
        <div id="userComments">
            <h3>
                <i class="fas fa-comments" data-fa-transform="shrink-1 up-2 right-2" style="background:#EF9A9A"></i>
                My Comments
            </h3>
            <div>
                <div class="list-group">
                    @foreach (var project in Model.MemberInProjects.Union(Model.OrganizerInProjects))
                    {
                        foreach (var assignment in project.Assignments)
                        {
                            foreach (var comment in assignment.Comments.Where(c => c.Author == Model))
                            {
                                <a href="@Url.Action("Details", "Comments", new { id = comment.CommentId})"
                                   class="list-group-item list-group-item-action">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">
                                            @Html.DisplayFor(modelItem => project.Title) | @Html.DisplayFor(modelItem => assignment.Title)
                                        </h5>
                                    </div>
                                    <p class="mb-1">
                                        @Html.DisplayFor(modelItem => comment.Content)
                                    </p>
                                    <small>
                                        @Html.DisplayFor(modelItem => comment.CreationDate)
                                    </small>
                                </a>
                            }
                        }
                    }

                </div>
            </div>
        </div>
        <div id="teamAssignments">
            <h3>
                <i class="fas fa-building" data-fa-transform="shrink-1 up-2 right-2" style="background:#EF9A9A"></i>
                Team Assignments
            </h3>
            <div>
                <div class="list-group">
                    @foreach (var project in Model.MemberInProjects.Union(Model.OrganizerInProjects))
                    {
                        foreach (var assignment in project.Assignments.Where(a => a.Assignee != Model))
                        {
                            <a href="@Url.Action("Details", "Assignments", new { id = assignment.AssignmentId })"
                               class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        @Html.DisplayFor(modelItem => project.Title) | @Html.DisplayFor(modelItem => assignment.Title)
                                    </h5>
                                </div>
                                <small>
                                    @Html.DisplayFor(modelItem => assignment.StartDate) - @Html.DisplayFor(modelItem => assignment.EndDate)
                                </small>
                            </a>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>Zilla</h1>
    <p class="lead">Aplicatie care face task-uri la proiecte la echipe la firme.</p>
    <br />
    <p><a href="@Url.Action("Dashboard", "Home")" class="btn btn-primary btn-lg">Dashboard &raquo;</a></p>
</div>

<div class="row">
</div>